export const OPERATIONS_STAGES = [
  {
    id: "d1",
    code: "S01",
    emoji: "📅",
    label: "D-1 준비",
    portalTitle: "내일 체크인 준비",
    portalDescription: "PIN, 웰컴 메시지, 스마트홈 준비가 덜 끝난 예약 숙소를 먼저 봅니다.",
    desc: "내일 체크인 전에 준비를 끝내는 단계입니다. PIN, 웰컴 메시지, 스마트홈 준비가 미리 끝났는지 확인합니다.",
    color: "#2563eb",
    bg: "#eff6ff",
    border: "#bfdbfe",
    scenarioScreen: "d1",
    filter: prop => prop.status === "예약됨" && prop.priority === "OK" && prop.unreadMsg === 0,
    portalFilter: prop => prop.status === "예약됨",
    batchActionLabel: "D-1 자동화 일괄 처리",
    decisionHint: "같은 단계 숙소가 여러 곳이면 D-1 일괄 처리로 넘깁니다.",
  },
  {
    id: "checkin",
    code: "S02",
    emoji: "🚪",
    label: "체크인 당일",
    portalTitle: "당일 입실 확인",
    portalDescription: "입실 직전 숙소 중 자동화가 끊기거나 응답이 필요한 예약 숙소를 봅니다.",
    desc: "입실 직전 또는 당일 개입이 필요한 예약 숙소를 모읍니다. 도어락 이벤트, 채널 오픈, 첫 메시지 대응을 놓치지 않는 단계입니다.",
    color: "#059669",
    bg: "#ecfdf5",
    border: "#a7f3d0",
    scenarioScreen: "s02",
    filter: prop => prop.status === "예약됨" && (prop.priority !== "OK" || prop.unreadMsg > 0),
    portalFilter: prop => prop.status === "예약됨" && (prop.priority !== "OK" || prop.unreadMsg > 0),
    batchActionLabel: "체크인 예외 일괄 처리",
    decisionHint: "입실 예외가 여러 건이면 체크인 당일 콘솔에서 묶어서 처리합니다.",
  },
  {
    id: "stay",
    code: "S03",
    emoji: "📡",
    label: "체류 중",
    portalTitle: "체류 중 대응",
    portalDescription: "센서 이상, 유지보수, 미응답 메시지처럼 사람이 바로 봐야 하는 숙소를 모읍니다.",
    desc: "체류 중 숙소를 관리하는 단계입니다. 센서 이상, 게스트 메시지, 현장 제어가 필요한 숙소를 먼저 찾습니다.",
    color: "#7c3aed",
    bg: "#f5f3ff",
    border: "#ddd6fe",
    scenarioScreen: "s03",
    filter: prop => prop.status === "입실중",
    portalFilter: prop => prop.status === "입실중" && (prop.priority === "HIGH" || prop.unreadMsg > 0 || prop.issues.length > 0),
    batchActionLabel: "체류 중 예외 일괄 처리",
    decisionHint: "센서 이상이나 메시지 예외가 여러 곳이면 체류 중 콘솔로 넘깁니다.",
  },
  {
    id: "checkout",
    code: "S04",
    emoji: "🧹",
    label: "퇴실·청소",
    portalTitle: "다음 예약 준비",
    portalDescription: "퇴실 이후 청소, 점검, 준비 완료 전환이 막힌 숙소를 정리합니다.",
    desc: "퇴실 이후 다음 예약 준비를 끝내는 단계입니다. 청소 배정, 유지보수, 준비 완료 전환이 여기서 관리됩니다.",
    color: "#d97706",
    bg: "#fffbeb",
    border: "#fde68a",
    scenarioScreen: "s04",
    filter: prop => prop.status === "청소중" || prop.status === "점검중",
    portalFilter: prop => prop.status === "청소중" || prop.status === "점검중" || prop.issues.length > 0,
    batchActionLabel: "퇴실·청소 일괄 처리",
    decisionHint: "청소와 점검 정체가 여러 곳이면 퇴실·청소 콘솔에서 묶어 처리합니다.",
  },
  {
    id: "settlement",
    code: "S05",
    emoji: "💰",
    label: "수익 정산",
    portalTitle: "정산 검토",
    portalDescription: "월 정산과 가격 판단에 사람이 검토할 숙소를 빠르게 모아 봅니다.",
    desc: "운영 흐름의 마지막 단계입니다. 월간 수익을 모으고 가격 추천과 정산 검토가 필요한 숙소를 봅니다.",
    color: "#0891b2",
    bg: "#ecfeff",
    border: "#a5f3fc",
    scenarioScreen: "s05",
    filter: () => true,
    portalFilter: prop => Number(prop.rating) < 4.3 || prop.revenue >= 500000,
    batchActionLabel: "수익 정산 일괄 처리",
    decisionHint: "정산이나 가격 검토가 한 번에 필요할 때 정산 콘솔로 넘깁니다.",
  },
];

export function getStageById(stageId) {
  return OPERATIONS_STAGES.find(stage => stage.id === stageId) || OPERATIONS_STAGES[0];
}

export function getPortalStageCards(props) {
  return OPERATIONS_STAGES.map(stage => ({
    ...stage,
    count: props.filter(stage.portalFilter || stage.filter).length,
  }));
}
